### ISSUE TITLE
Calling same code fails first time.

### ISSUE THREAD

**Issue by clienthax** [zml2008/configurate#39]
calling this code will fail the first time with a error while getting the uuidNode,
the second time it is run, it saves fine
```
	public void saveClaims() {

		try {
			CommentedConfigurationNode mainNode = MainMod.goldenShovelConfig.load();
			CommentedConfigurationNode claimsNode = mainNode.getNode("Claims");

			for(HashMap.Entry<UUID, ArrayList<ClaimEntry>> uuidEntry : claimEntries.entrySet()) {
				CommentedConfigurationNode uuidNode = claimsNode.getNode(uuidEntry.getKey().toString());
				ArrayList<HashMap<String,Object>> regionDatas = new ArrayList<>();
				for(ClaimEntry claimEntry : uuidEntry.getValue()) {
					HashMap<String, Object> claimHashMap = new HashMap<>();
					claimHashMap.put("data",claimEntry.getData());
					regionDatas.add(claimHashMap);
				}
				uuidNode.setValue(regionDatas);
			}


			MainMod.goldenShovelConfig.save(mainNode);
		} catch (Exception e) {
			claimEntries.clear();
			e.printStackTrace();
		}

	}
```
```
[19:29:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.UUID
[19:29:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at uk.co.haxyshideout.pixelmon.protection.GoldenShovelStore.saveClaims(GoldenShovelStore.java:62)
[19:29:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at uk.co.haxyshideout.pixelmon.protection.GoldenShovelStore.createClaim(GoldenShovelStore.java:110)
[19:29:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at uk.co.haxyshideout.pixelmon.protection.GoldenShovelStore.createClaim(GoldenShovelStore.java:103)
[19:29:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at uk.co.haxyshideout.pixelmon.protection.GoldenShovelStore.createChestClaim(GoldenShovelStore.java:97)
[19:29:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at uk.co.haxyshideout.pixelmon.eventhandlers.GoldenShovelHandler.onChestPlacement(GoldenShovelHandler.java:25)
```

**Comment by clienthax** [comment]
When replacing the save code with
`claimsNode.setValue(new TypeToken<Map<UUID, ArrayList<ClaimEntry>>>(){}, claimEntries);`
and saving, the following is produced
[20:02:45] [Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: com.typesafe.config.ConfigException$BugOrBroken: bug in method caller: not valid to create ConfigValue from: ac42e7c5-bf90-3ead-ba50-c551df161044

**Comment by zml2008** [comment]
ok, thing that comes up: would doing Map<UUID, List<ClaimEntry>> instead work for you? that's really the only thing I can think of right now

**Comment by zml2008** [comment]
fixed in irc, closing
