### ISSUE TITLE
Exception when using using 3.0 hocon configuration loader

### ISSUE THREAD

**Issue by SonarBeserk** [zml2008/configurate#47]
When trying to use the hocon configuration loader I get the following exception.

```
Caused by: java.lang.NoSuchMethodError: com.typesafe.config.impl.ConfigImpl.newSimpleOrigin(Ljava/lang/String;)Lcom/typesafe/config/ConfigOrigin;
	at com.typesafe.config.ConfigOriginFactory.newSimple(ConfigOriginFactory.java:42)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.<clinit>(HoconConfigurationLoader.java:155)
	at net.catharos.commons.Configuration.<init>(Configuration.java:53)
	at net.catharos.commons.Configuration.<init>(Configuration.java:40)
	at net.catharos.commons.Settings.<init>(Settings.java:28)
	at net.catharos.client.ClientSettings.<init>(ClientSettings.java:22)
	... 52 more
```

**Comment by zml2008** [comment]
This means you haven't shaded hocon correctly
