### ISSUE TITLE
Missing TypeSerializer for char

### ISSUE THREAD

**Issue by games647** [zml2008/configurate#53]
I get NPEs if I want to use char types with the ObjectMapper.

Stacktrace:

```
java.lang.NullPointerException
        at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.serializeTo(ObjectMapper.java:105) ~[ObjectMapper$FieldData.class:1.8-1577-3.1.0-BETA-1024]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.deserializeFrom(ObjectMapper.java:87) ~[ObjectMapper$FieldData.class:1.8-1577-3.1.0-BETA-1024]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.populate(ObjectMapper.java:140) ~[ObjectMapper$BoundInstance.class:1.8-1577-3.1.0-BETA-1024]
        at com.github.games647.healthname.config.Settings.load(Settings.java:55) ~[Settings.class:?]
        at com.github.games647.healthname.HealthName.onPreInit(HealthName.java:60) ~[HealthName.class:?]
        at org.spongepowered.common.event.listener.GamePreInitializationEventListener_HealthName_onPreInit4.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:86) ~[RegisteredListener.class:1.8-1577-3.1.0-BETA-1024]
```

The code I used:
[Config object](https://github.com/games647/HealthName/blob/b786b1efcfa03b7136d0e5596bad39002125f0ae/src/main/java/com/github/games647/healthname/config/Config.java)
[Loader](https://github.com/games647/HealthName/blob/b786b1efcfa03b7136d0e5596bad39002125f0ae/src/main/java/com/github/games647/healthname/config/Settings.java)
When I tried to change the char to a String, it works fine without any exceptions.

**Comment by zml2008** [comment]
Don't use a `char` type -- it has issues with multibyte unicode codepoints.
