### ISSUE TITLE
NPE instead of clear error in case of missing Serializer for type

### ISSUE THREAD

**Issue by vorburger** [zml2008/configurate#61]
The following NPE which I just hit appears to occur when a Serializer for a Type is missing?

It would be nicer, of course, if there as a clearer Exception / message indicating this.

Would you welcome and merge a PR suggesting an improvement in error handling related to this?

```
Caused by: java.lang.NullPointerException
	at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.serializeTo(ObjectMapper.java:105) ~[configurate-core-3.1.1.jar:?]
	at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.serialize(ObjectMapper.java:154) ~[configurate-core-3.1.1.jar:?]
	at ch.vorburger.minecraft.config.ConfigurationPersister.save(ConfigurationPersister.java:65) ~[?:?]
```

**Comment by zml2008** [comment]
Fixed in 1a91e30b41d99406104a0e1731b354d9f911931c
