### ISSUE TITLE
Handle substitutions

### ISSUE THREAD

**Issue by pie-flavor** [zml2008/configurate#65]
Exception is thrown when attempting to load a .conf file with $ substitutions.
```
java.io.IOException: com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${templates.treasure-chance})
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:157)
	at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:42)
```
...
```
Caused by: com.typesafe.config.ConfigException$NotResolved: need to Config#resolve(), see the API docs for Config#resolve(); substitution not resolved: ConfigReference(${templates.treasure-chance})
	at com.typesafe.config.impl.ConfigReference.notResolved(ConfigReference.java:33)
	at com.typesafe.config.impl.ConfigReference.valueType(ConfigReference.java:40)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.readConfigValue(HoconConfigurationLoader.java:114)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.readConfigValue(HoconConfigurationLoader.java:120)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.readConfigValue(HoconConfigurationLoader.java:127)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:106)
	at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:54)
	at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:149)
```
Yes, the path exists. No, I didn't bungle anything.

**Comment by ryantheleach** [comment]
With the substitutions though, does this work with merging?
