### ISSUE TITLE
TypeToken.isSupertypeOf no such as method.

### ISSUE THREAD

**Issue by nikosgram13** [zml2008/configurate#79]
I'm tried to use your API in the Bukkit's API and happens that.

```
[21:57:45] [Server thread/ERROR]: com.google.common.reflect.TypeToken.isSupertypeOf(Lcom/google/common/reflect/TypeToken;)Z initializing OlgofusProtection v1.0.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: com.google.common.reflect.TypeToken.isSupertypeOf(Lcom/google/common/reflect/TypeToken;)Z
	at ninja.leaping.configurate.objectmapping.serialize.TypeSerializerCollection.get(TypeSerializerCollection.java:45) ~[?:?]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:215) ~[?:?]
	at ninja.leaping.configurate.SimpleConfigurationNode.getList(SimpleConfigurationNode.java:141) ~[?:?]
	at ninja.leaping.configurate.ConfigurationNode.getList(ConfigurationNode.java:180) ~[?:?]
	at com.oglofus.protection.OglofusPlugin.onLoad(OglofusPlugin.java:210) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-3fb9445-6e3cec8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

My code:
```java
ndoe.getList(TypeToken.of(SimpleConfigurationNode.class));
```

Can you update the Guava API on the latest version?

**Comment by zml2008** [comment]
It's spigot's guava that's outdated. Use configurate 3.2 instead until you want to support spigot 1.12

**Comment by nikosgram13** [comment]
@zml2008 Thank you mate, I didn't see that. Soz.
